### ISSUE TITLE
hard to find stack trace in eden log

### ISSUE THREAD

**Issue by deitch** [lf-edge/eden#238]
I had a panic in volumemgr.`eden log` showed the regular logs and `panic`, but not the stack traces. But they were there in `/pillar/rsyslog/syslog.txt`

**Comment by giggsoff** [comment]
Is it problem of Eden? Can you please search through channels of redis?

**Comment by deitch** [comment]
Sure. Tell me what I am looking for and how?

**Comment by giggsoff** [comment]
Please run:
```
docker exec -it eden_redis /bin/bash
redis-cli keys LOGS_*
redis-cli xread STREAMS LOGS_EVE_dc3324b6-ca1f-4843-83b8-58b004575f76 0|grep panic
```
where `LOGS_EVE_dc3324b6-ca1f-4843-83b8-58b004575f76` - is output of `redis-cli keys LOGS_*` command

**Comment by deitch** [comment]
That helped. It turns out the stack trace _is_ there, but is hard to determine. I will change the title of the issue.

**Comment by deitch** [comment]
Here is a sample stack trace I induced by causing an index out of bounds exception.

First, the original log from `/persist/rsyslog/syslog.txt`:

```
2020-08-25T10:21:50.992887+00:00 linuxkit-525400123456 pillar.err 2020-08-25T10:21:50Z,pillar.err;panic: runtime error: index out of range
2020-08-25T10:21:51.001122+00:00 linuxkit-525400123456 pillar.err 2020-08-25T10:21:50Z,pillar.err;
2020-08-25T10:21:51.030452+00:00 linuxkit-525400123456 pillar.err 2020-08-25T10:21:50Z,pillar.err;goroutine 1 [running]:
2020-08-25T10:21:51.037369+00:00 linuxkit-525400123456 pillar.err 2020-08-25T10:21:50Z,pillar.err;github.com/lf-edge/eve/pkg/pillar/cmd/volumemgr.doUpdateContentTree(0xc00046ca80, 0xc0001e03
2020-08-25T10:21:51.047754+00:00 linuxkit-525400123456 pillar.out {"file":"/pillar/cmd/zedagent/parseconfig.go:1451","func":"github.com/lf-edge/eve/pkg/pillar/cmd/zedagent.parseUnderlayNetwo
2020-08-25T10:21:51.056504+00:00 linuxkit-525400123456 pillar.out {"file":"/pillar/cmd/zedagent/parseconfig.go:520","func":"github.com/lf-edge/eve/pkg/pillar/cmd/zedagent.parseAppInstanceCon
2020-08-25T10:21:51.092566+00:00 linuxkit-525400123456 pillar.err 2020-08-25T10:21:50Z,pillar.err;      /pillar/cmd/volumemgr/updatestatus.go:220 +0x365c
2020-08-25T10:21:51.104269+00:00 linuxkit-525400123456 pillar.err 2020-08-25T10:21:50Z,pillar.err;github.com/lf-edge/eve/pkg/pillar/cmd/volumemgr.updateContentTree(0xc00046ca80, 0xc0001e03c0
2020-08-25T10:21:51.110450+00:00 linuxkit-525400123456 pillar.err 2020-08-25T10:21:50Z,pillar.err;      /pillar/cmd/volumemgr/handlecontent.go:257 +0xb2
2020-08-25T10:21:51.115982+00:00 linuxkit-525400123456 pillar.err 2020-08-25T10:21:50Z,pillar.err;github.com/lf-edge/eve/pkg/pillar/cmd/volumemgr.handleContentTreeCreateAppImg(0x16a5520, 0xc
2020-08-25T10:21:51.121967+00:00 linuxkit-525400123456 pillar.err 2020-08-25T10:21:50Z,pillar.err;      /pillar/cmd/volumemgr/handlecontent.go:21 +0x1f5
2020-08-25T10:21:51.131296+00:00 linuxkit-525400123456 pillar.out {"file":"/pillar/cmd/zedagent/handlecipherconfig.go:81","func":"github.com/lf-edge/eve/pkg/pillar/cmd/zedagent.parseCipherBl
2020-08-25T10:21:51.137568+00:00 linuxkit-525400123456 pillar.out {"file":"/pillar/cmd/zedagent/handlecipherconfig.go:83","func":"github.com/lf-edge/eve/pkg/pillar/cmd/zedagent.parseCipherBl
2020-08-25T10:21:51.144265+00:00 linuxkit-525400123456 pillar.err 2020-08-25T10:21:50Z,pillar.err;github.com/lf-edge/eve/pkg/pillar/pubsub.handleModify(0x17f2c60, 0xc0004ec380, 0xc0002bb260,
2020-08-25T10:21:51.152633+00:00 linuxkit-525400123456 pillar.err 2020-08-25T10:21:50Z,pillar.err;      /pillar/pubsub/subscribe.go:227 +0x6d5
2020-08-25T10:21:51.190357+00:00 linuxkit-525400123456 pillar.err 2020-08-25T10:21:50Z,pillar.err;github.com/lf-edge/eve/pkg/pillar/pubsub.(*SubscriptionImpl).ProcessChange(0xc0004ec380, 0x3
2020-08-25T10:21:51.198410+00:00 linuxkit-525400123456 pillar.err 2020-08-25T10:21:50Z,pillar.err;      /pillar/pubsub/subscribe.go:105 +0x31c
```

And now from eden log:

```
source: pillar.out
level: emerg
msg: 2020-08-25T10:24:51Z,pillar.out;2020-08-25T10:21:50.992887+00:00 linuxkit-525400123456 pillar.err 2020-08-25T10:21:50Z,pillar.err;panic: runtime error: index out of range
file:
func:
time: 2020-08-25T10:24:59.783163+00:00
pid: 0
partition: IMGA

source: pillar.err
level: emerg
msg: 2020-08-25T10:21:50Z,pillar.err;goroutine 1 [running]:
file:
func:
time: 2020-08-25T10:21:51.030452+00:00
pid: 0
partition: IMGA

source: pillar.err
level: emerg
msg: 2020-08-25T10:21:50Z,pillar.err;github.com/lf-edge/eve/pkg/pillar/cmd/volumemgr.doUpdateContentTree(0xc00046ca80, 0xc0001e03c0, 0x18)
file:
func:
time: 2020-08-25T10:21:51.037369+00:00
pid: 0
partition: IMGA

source: pillar.err
level: emerg
msg: 2020-08-25T10:21:50Z,pillar.err;   /pillar/cmd/volumemgr/updatestatus.go:220 +0x365c
file:
func:
time: 2020-08-25T10:21:51.092566+00:00
pid: 0
partition: IMGA
```

And in json:

```json
{"source":"pillar.err","level":"emerg","msg":"2020-08-25T10:21:50Z,pillar.err;panic: runtime error: index out of range","file":"","func":"","time":"2020-08-25T10:21:50.992887+00:00","pid":0,"partition":"IMGA"}
{"source":"volumemgr","level":"info","msg":"Content tree config create","file":"/pillar/types/contenttreetypes.go:47","func":"github.com/lf-edge/eve/pkg/pillar/types.ContentTreeConfig.LogCreate","time":"2020-08-25T10:21:49.990936041Z","pid":2203,"partition":""}
{"source":"volumemgr","level":"info","msg":"handleContentTreeCreateAppImg(f101163a-796d-4b2f-b277-f4116dd03061)","file":"/pillar/cmd/volumemgr/handlecontent.go:17","func":"github.com/lf-edge/eve/pkg/pillar/cmd/volumemgr.handleContentTreeCreateAppImg","time":"2020-08-25T10:21:49.994508872Z","pid":2203,"partition":""}
{"source":"pillar.err","level":"emerg","msg":"2020-08-25T10:21:50Z,pillar.err;","file":"","func":"","time":"2020-08-25T10:21:51.001122+00:00","pid":0,"partition":"IMGA"}
{"source":"volumemgr","level":"info","msg":"createContentTreeStatus for f101163a-796d-4b2f-b277-f4116dd03061 objType appImg.obj","file":"/pillar/cmd/volumemgr/handlecontent.go:154","func":"github.com/lf-edge/eve/pkg/pillar/cmd/volumemgr.createContentTreeStatus","time":"2020-08-25T10:21:49.997406021Z","pid":2203,"partition":""}
{"source":"pillar.err","level":"emerg","msg":"2020-08-25T10:21:50Z,pillar.err;goroutine 1 [running]:","file":"","func":"","time":"2020-08-25T10:21:51.030452+00:00","pid":0,"partition":"IMGA"}
{"source":"volumemgr","level":"info","msg":"lookupContentTreeStatus(f101163a-796d-4b2f-b277-f4116dd03061/appImg.obj)","file":"/pillar/cmd/volumemgr/handlecontent.go:124","func":"github.com/lf-edge/eve/pkg/pillar/cmd/volumemgr.lookupContentTreeStatus","time":"2020-08-25T10:21:50.000294205Z","pid":2203,"partition":""}
{"source":"volumemgr","level":"info","msg":"lookupContentTreeStatus(f101163a-796d-4b2f-b277-f4116dd03061/appImg.obj) not found","file":"/pillar/cmd/volumemgr/handlecontent.go:128","func":"github.com/lf-edge/eve/pkg/pillar/cmd/volumemgr.lookupContentTreeStatus","time":"2020-08-25T10:21:50.017226002Z","pid":2203,"partition":""}
{"source":"pillar.err","level":"emerg","msg":"2020-08-25T10:21:50Z,pillar.err;github.com/lf-edge/eve/pkg/pillar/cmd/volumemgr.doUpdateContentTree(0xc00046ca80, 0xc0001e03c0, 0x18)","file":"","func":"","time":"2020-08-25T10:21:51.037369+00:00","pid":0,"partition":"IMGA"}
{"source":"pillar.err","level":"emerg","msg":"2020-08-25T10:21:50Z,pillar.err;\t/pillar/cmd/volumemgr/updatestatus.go:220 +0x365c","file":"","func":"","time":"2020-08-25T10:21:51.092566+00:00","pid":0,"partition":"IMGA"}
```

So eden looks to be doing the right thing, but getting those stack traces understood is hard.

I am beginning to think that this isn't a problem for _eden_ as it is for _eve_. Thoughts on it @rvs ?

**Comment by giggsoff** [comment]
So, as I can see, EVE splits this message into multiple [LogEntry](https://github.com/lf-edge/eve/blob/075888d90febfd9eed089accaa1a4cdbcf90a7b9/api/go/logs/log.pb.go#L155).

**Comment by deitch** [comment]
I think you are right. This is one of those that needs to be handled correctly. I think @rvs would know how to fix this. 

I will open a parallel issue in eve and then we can close this out.

**Comment by deitch** [comment]
Closing in favour of the eve issue.
